resume:
pretrain: /home/cjm/AutoBio/ActionCLIP/exp/clip_k400/ViT-B/32/autobio/model_best_transf.pt
seed: 1024
data:
    dataset: autobio_trans
    modality: RGB
    num_segments: 8
    seg_length: 1
    batch_size: 4
    workers: 16
    num_classes: 20
    image_tmpl: 'img_{:05d}.jpg'
    train_list: '/home/cjm/AutoBio/ActionCLIP/data/autobio/autobio_train_frames_133.txt'
    val_list: '/home/cjm/AutoBio/ActionCLIP/data/autobio/autobio_val_frames.txt' #
    label_list: '/home/cjm/AutoBio/ActionCLIP/data/autobio/autobio_labels.csv'
    index_bias: 1
    input_size: 224
    randaug:
        N: 2 #2
        M: 9  #9
    random_shift: True
network:
    arch: ViT-B/32  #ViT-B/32 ViT-B/16
    init: True
    tsm: False
    drop_out: 0.0 
    emb_dropout: 0.0 
    type: clip_k400
    sim_header: "Transf"  #Transf   meanP  LSTM Conv_1D Transf_cls
#    sim_header: "Transf"  #Transf   meanP  LSTM Conv_1D Transf_cls
    joint: False
    describe:
solver:
    type: cosine
    epochs: 10
    start_epoch: 0
    epoch_offset: 0
    optim: adamw
    lr: 5.e-6
    lr_warmup_step: 5
    momentum: 0.9
    weight_decay: 0.2
    lr_decay_step: 15
    lr_decay_factor: 0.1
    clip_gradient: 20
    loss_type: nll
    evaluate: False
    ratio: 1
    f_ratio: 10
logging:
    print_freq: 10
    eval_freq: 1